/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gr
 */
public class ServiceView extends javax.swing.JInternalFrame  {

    /**
     * Creates new form ServiceView
     */
    public ServiceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane7 = new javax.swing.JScrollPane();
        billList = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();
        designation = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        Rechercher2 = new javax.swing.JTextField();
        AddServiceButton = new javax.swing.JButton();
        DeleteServiceButton = new javax.swing.JButton();
        EditServiceButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        billList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Désignation", "Description"
            }
        ));
        billList.setGridColor(new java.awt.Color(0, 153, 153));
        billList.setRowHeight(25);
        billList.setRowMargin(1);
        jScrollPane7.setViewportView(billList);

        jLabel46.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel46.setText("DESIGNATION");

        designation.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel49.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel49.setText("DESCRIPTION");

        description.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N

        jLabel50.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel50.setText("Rechercher");

        Rechercher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rechercher2ActionPerformed(evt);
            }
        });
        Rechercher2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Rechercher2KeyReleased(evt);
            }
        });

        AddServiceButton.setBackground(new java.awt.Color(51, 153, 0));
        AddServiceButton.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        AddServiceButton.setForeground(new java.awt.Color(255, 255, 255));
        AddServiceButton.setText("AJOUTER");

        DeleteServiceButton.setBackground(new java.awt.Color(153, 0, 51));
        DeleteServiceButton.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        DeleteServiceButton.setForeground(new java.awt.Color(255, 255, 255));
        DeleteServiceButton.setText("SUPPRIMER");
        DeleteServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteServiceButtonActionPerformed(evt);
            }
        });

        EditServiceButton.setBackground(new java.awt.Color(0, 102, 255));
        EditServiceButton.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        EditServiceButton.setForeground(new java.awt.Color(255, 255, 255));
        EditServiceButton.setText("MODIFIER");
        EditServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditServiceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddServiceButton)
                        .addGap(173, 173, 173)
                        .addComponent(EditServiceButton)
                        .addGap(171, 171, 171)
                        .addComponent(DeleteServiceButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(designation, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(description))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(Rechercher2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(designation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Rechercher2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddServiceButton)
                    .addComponent(DeleteServiceButton)
                    .addComponent(EditServiceButton))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rechercher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rechercher2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rechercher2ActionPerformed

    private void Rechercher2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Rechercher2KeyReleased

        /* try {
            ps = con.prepareStatement("SELECT client.id AS Matricule , client.nom AS Firstname , categorie.intitule AS CategorieName FROM Client JOIN Categorie ON client.categorie_id=categorie.id where nom like ? ");
            ps.setString(1,"%" +Rechercher.getText() + "%");
            rs=ps.executeQuery();
            // TableClients.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            System.err.print(ex.getMessage());// fonction pour rechercher en tapant n'importe quoi
        }*/
        // TODO add your handling code here:
    }//GEN-LAST:event_Rechercher2KeyReleased

    private void DeleteServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteServiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteServiceButtonActionPerformed

    private void EditServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditServiceButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditServiceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddServiceButton;
    private javax.swing.JButton DeleteServiceButton;
    private javax.swing.JButton EditServiceButton;
    private javax.swing.JTextField Rechercher2;
    private javax.swing.JTable billList;
    private javax.swing.JTextField description;
    private javax.swing.JTextField designation;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
